[package]
name = "hello_macro_derive"
version = "0.1.0"
edition = "2021"

# syn 和 quote 依赖包都是定义过程宏所必需的，
# 同时，还需要在 [lib] 中将过程宏的开关开启 : proc-macro = true。
[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
